name: Publish to Packagist

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to Packagist
        uses: paquettg/packagist-github-actions@v1
        with:
          api_token: ${{ secrets.PACKAGIST_API_TOKEN }}
          package_name: ${{ secrets.PACKAGIST_PACKAGE_NAME }}
        env:
          GIT_DEPTH: 0
